# Generated by Django 2.0.3 on 2018-08-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_product_affiliate_url'),
        ('product', '0067_remove_product_is_featured'),
    ]

    operations = [
    ]
