# Generated by Django 2.0.3 on 2018-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_merge_20180813_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='affiliate_url',
            field=models.URLField(blank=True, default=None, help_text='Insert the Affiliate Product Url which will replace Add to Cart button with Affiliate Url Click', max_length=500, null=True),
        ),
    ]
