# Generated by Django 2.0.3 on 2018-08-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_auto_20180730_1125'),
        ('shipping', '0011_auto_20180802_1238'),
    ]

    operations = [
    ]
