version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: saleor-web
    restart: unless-stopped
    networks:
      - saleor-backend-tier
      - nginx_network
    ports:
      - 8000:8000
    #volumes:
    #  - saleor-app:/app:Z
    env_file: common.env
    depends_on:
      - db
      - redis
      - search

  db:
    image: library/postgres:latest
    container_name: saleor-postgres
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:latest
    container_name: saleor-redis
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: saleor-celery
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    #volumes:
    #  - saleor-app:/app:Z
    env_file: common.env
    depends_on:
      - redis

  search:
    image: elasticsearch:5.4.3
    container_name: saleor-elasticsearch
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    ports:
      - 9200:9200
    # See https://github.com/docker/compose/issues/4513 if updating to version '3'
    mem_limit: 512m
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  nginx:
    container_name: dsne-nginx
    image: nginx:1.13
    ports:
      - 80:80
    networks:
      - nginx_network
    volumes:
      - ./nginx:/etc/nginx/conf.d
      #- /docker/letsencrypt-docker-nginx/src/letsencrypt/letsencrypt-site:/usr/share/nginx/html
      #- dsne-django-static:/app/static/
    depends_on:
      - web

#volumes:
#  saleor-app:
#    driver: local

networks:
  saleor-backend-tier:
    driver: bridge
  nginx_network:
    driver: bridge
