version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - database1_network
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: common.env
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    links:
      - redis
    depends_on:
      - redis
  search:
    image: elasticsearch:5.4.3
    mem_limit: 512m
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '127.0.0.1:9200:9200'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: common.env
    depends_on:
      - db
      - redis
      - search
    networks:
      - nginx_network
      - database1_network

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - dsne-django-static:/app/static  # <-- bind the static volume
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  dsne-django-static:

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge
