# Generated by Django 2.0.3 on 2018-08-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_cart_translated_discount_name'),
        ('checkout', '0009_auto_20180730_1125'),
    ]

    operations = [
    ]
