# Generated by Django 2.0.3 on 2018-08-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_auto_20180730_1125'),
        ('order', '0051_merge_20180807_0704'),
    ]

    operations = [
    ]
